### ISSUE TITLE
Certain messages cause proxy server to crash

### ISSUE THREAD

**Issue by regnull** [regnull/ubikom#34]
00:52:01 DBG reading messages prefix=message_1AfUuN7SRnm8o7ZieSeNZTh2ibjFj9exGK_1_
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8c pc=0x81d679]

goroutine 107 [running]:
github.com/emersion/go-imap.(*Message).formatItem(0xc000445500, {0xc0046f6370, 0xd})
	/Users/regnull/go/pkg/mod/github.com/emersion/go-imap@v1.2.0/message.go:286 +0x339
github.com/emersion/go-imap.(*Message).Format(0xc000445500)
	/Users/regnull/go/pkg/mod/github.com/emersion/go-imap@v1.2.0/message.go:323 +0x33e
github.com/emersion/go-imap/responses.(*Fetch).WriteTo(0xc000068900, 0xc0004f81e0)
	/Users/regnull/go/pkg/mod/github.com/emersion/go-imap@v1.2.0/responses/fetch.go:64 +0x85
github.com/emersion/go-imap/server.(*response).WriteTo(0xc000494258, 0xc62d20)
	/Users/regnull/go/pkg/mod/github.com/emersion/go-imap@v1.2.0/server/conn.go:130 +0x29
github.com/emersion/go-imap/server.(*conn).writeAndFlush(0xc002280a80, {0xc633a0, 0xc000494258})
	/Users/regnull/go/pkg/mod/github.com/emersion/go-imap@v1.2.0/server/conn.go:208 +0x35
github.com/emersion/go-imap/server.(*conn).send(0xc002280a80)
	/Users/regnull/go/pkg/mod/github.com/emersion/go-imap@v1.2.0/server/conn.go:232 +0x227
created by github.com/emersion/go-imap/server.newConn
	/Users/regnull/go/pkg/mod/github.com/emersion/go-imap@v1.2.0/server/conn.go:111 +0x352

**Comment by regnull** [comment]
The code in question:

switch k {
	case FetchBody, FetchBodyStructure:
		// Extension data is only returned with the BODYSTRUCTURE fetch
		m.BodyStructure.Extended = k == FetchBodyStructure   <==== This line
		v = m.BodyStructure.Format()

**Comment by regnull** [comment]
It is possibly related to this error:

00:57:00 ERR failed to create email entity error="unknown charset: unknown charset: message: unhandled charset \"ascii\""
00:57:00 ERR failed to create email entity error="unknown charset: unknown charset: message: unhandled charset \"iso-8859-1\""
00:57:00 ERR failed to create email entity error="unknown charset: unknown charset: message: unhandled charset \"windows-1252\""

**Comment by regnull** [comment]
Fixed by https://github.com/regnull/ubikom/commit/5743bfc52ad3def71a4e0e79988e718f7ba4304a

Unknown charset message is still there, but it doesn't crash the server (presumably, messages that cause this error are not displayed).
